name: CI/CD Deployemnt

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'kubernetes/deployment.yaml'
  pull_request: 
    branches: [ main ]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: action/checkout@v4

      - name: Setup node
        uses: action/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm Install

      - name: Run tests
        run : npn test || echo "No tests found, would add tests in a real project"


